Awesome Books - ES6 Compatible
ehmaddd/Awesome-books-with-ES6 pull request #1
Opened 2023-03-27 22:13 UTC by ehmaddd

This project is the modification of the previous project which was created to view, add and delete books from the webpage divided into sections. In this update, the whole project is divided into different modules and every module is included in the main JS File which gives and takes data to/from the module file. The module is basically a chunk of code separated to avoid the mess in the main file. Moreover, Luxon is used to getting live date/times on the webpage.

2023-03-27 23:00 UTC, ouasamine requested changes
Hi @ehmaddd 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
- Nice work using the ES6 syntax correctly 👏🏽 👏🏽 
- Your code is well organised, good job ✔️ ✔️ 
- Good project's documentation 👍🏽 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 03:43 UTC, ehmaddd commented on modules/book-auth.js
> +export default bookAuth;
Thanks for the complement. I have made changes as per instructions. Double export is removed.

2023-03-28 03:43 UTC, ehmaddd commented on modules/data-display.js
> +export default dataDisplay;
Changes have been made as instructed.

2023-03-28 03:43 UTC, ehmaddd commented on modules/nav-dynamics.js
> +export default navBar;
Changes have been made as instructed.

2023-03-28 03:43 UTC, ehmaddd commented on modules/remove-list.js
> +export default removeList;
Changes have been made as instructed.

2023-03-28 03:43 UTC, ehmaddd commented on modules/show-time.js
> +export default showTime;
Changes have been made as instructed.

2023-03-28 03:43 UTC, ehmaddd commented on modules/window-load.js
> +export default windowLoad;
Changes have been made as instructed.

2023-03-28 03:44 UTC, ehmaddd commented on index.html
> +    </header>
Thanks for the kind patronization. I've changed the default space to 2 and also will change the default size of tab key in VS Code.

2023-03-28 03:56 UTC, shella12 approved these changes
Hi @ehmaddd , 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great UI 👍 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 04:00 UTC, merged